package akira.lecovian;

import com.google.common.eventbus.EventBus;
import com.google.common.eventbus.Subscribe;

import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.client.event.TextureStitchEvent;

import net.minecraftforge.fml.common.DummyModContainer;
import net.minecraftforge.fml.common.LoadController;
import net.minecraftforge.fml.common.ModMetadata;

import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLLoadCompleteEvent;

import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;

import java.util.Arrays;

public final class LecovianModContainer extends DummyModContainer {

    public static final String MODID = "lecovian";

    public LecovianModContainer() {
        super(new ModMetadata());

        ModMetadata meta = getMetadata();
        meta.modId = MODID;
        meta.name = "Lecovian";
        meta.version = "1.0.0";
        meta.description = "Per-entity texture variance / recolor";
        meta.authorList = Arrays.asList("akira");
        meta.credits = "Lecovian variant system";
        meta.autogenerated = false;
    }

    // Forge calls this to hook us up to the FML lifecycle bus (which is Guava EventBus here)
    @Override
    public boolean registerBus(EventBus bus, LoadController controller) {
        bus.register(this);
        return true;
    }

    // FMLPreInitializationEvent fires here via Guava's bus
    @Subscribe
    public void onPreInit(FMLPreInitializationEvent e) {
        System.out.println("[Lecovian] preInit — writing config baseline if needed (DummyModContainer)");

        // Create/sync config so a cfg file appears even in an otherwise empty profile
        ConfigFiles.loadOrCreate(e.getModConfigurationDirectory());

        // Hook render cache invalidation on texture reloads
        MinecraftForge.EVENT_BUS.register(new TextureEvents());
    }

    // After *everything* loads, we rescan entities and rewrite sigma list so you get all mobs in the cfg
    @Subscribe
    public void onLoadComplete(FMLLoadCompleteEvent e) {
        ConfigFiles.rescanEntities();
    }

    // This one listens on the normal Forge EVENT_BUS (not Guava)
    public static final class TextureEvents {
        @SubscribeEvent
        public void onTextureStitch(TextureStitchEvent.Post ev) {
            VariantManager.clearAll();
        }
    }
}
